name: CI/CD pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v2

      - name: setup the python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.14.0-alpha.7'

      - name: install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run tests        
        run: |
          echo "Running tests..."
          echo "NO tests found"

# dockerize:
#   build:
#     runs-on: ubuntu-latest
#     steps:
      - name: checkout the code
        uses: actions/checkout@v2          

      - name: Build the docker image
        run : |
          echo "Building the docker image..."
          docker build -t python-application:latest .
          echo "Docker image built successfully"

      - name: run the docker container
        run: |
          echo "Running the docker container..."
          docker run -d -p 5000:5000 python-application:latest
          echo "Docker container is running"      